"""TypeScript types/client generation from the Command Center OpenAPI (P5-7).

Deterministic, stdlib-only generator: given the OpenAPI 3.1 document produced
by ``build_openapi(...)`` it emits two artifacts under
``command_center/generated/ts/``:

- ``types.ts`` — OpenAPI schema -> TypeScript types. Every operation gets an
  ``<OperationId>Params`` interface (typed query/path parameters) and an
  ``<OperationId>Response`` alias derived from the 200 application/json
  schema. Distinct enum value sets found in the document become named union
  types (``Tenant`` / ``TenantWithAll``) via a deterministic value-set
  mapping; any other enum stays inline.
- ``client.ts`` — a lightweight fetch wrapper (timeout + no-store + weak-ETag
  304 negotiation + error mapping) plus one typed function per operation,
  grouped by the path prefix (``/api/shop/*`` -> tag ``shop``).

Determinism: the same ``build_openapi`` input always produces byte-identical
output (sorted traversal, LF line endings, no timestamps). Fail-fast: any
schema construct the generator cannot map to TypeScript (unknown keyword,
missing ``$ref`` target, ``not``, array without ``items``, unknown ``type``,
enum/type mismatch) raises :class:`TsGenError` instead of silently degrading.
The empty schema ``{}`` (OpenAPI "any value") maps to ``unknown`` by design,
so today every response type is ``unknown`` (the P5-5 document does not carry
response schemas yet); client functions keep the response type generic
(``<T = XxxResponse>``) so callers can supply a concrete type.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from .openapi import build_openapi
from .routes import RouteTable

GENERATED_DIR = Path(__file__).resolve().parents[1] / "generated" / "ts"
ARTIFACT_NAMES = ("types.ts", "client.ts")

_HEADER = """/* AUTO-GENERATED by tsgen.py - DO NOT EDIT.
 * Source: build_openapi(RouteTable()) OpenAPI 3.1 document
 * (docs/command-center/openapi-v1.json).
 * Regenerate: uv run python -m arena_hero_agent.command_center.api.tsgen --emit
 */
"""

# Schema keywords that carry type-shape information and are supported.
_STRUCTURAL_KEYS = frozenset(
    {
        "type",
        "enum",
        "items",
        "properties",
        "required",
        "additionalProperties",
        "$ref",
        "oneOf",
        "anyOf",
        "allOf",
        "nullable",
    }
)
# Metadata keywords accepted and ignored (they do not change the TS shape).
_METADATA_KEYS = frozenset(
    {
        "description",
        "title",
        "example",
        "examples",
        "default",
        "format",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "minLength",
        "maxLength",
        "pattern",
        "deprecated",
        "readOnly",
        "writeOnly",
        "minItems",
        "maxItems",
        "uniqueItems",
        "minProperties",
        "maxProperties",
    }
)

# Deterministic name derivation for the tenant enum value sets found in the
# document. Any other enum stays inline in the Params interface.
_ENUM_TYPE_NAMES: dict[frozenset[str], str] = {
    frozenset({"t1", "t2", "t3", "t4"}): "Tenant",
    frozenset({"all", "t1", "t2", "t3", "t4"}): "TenantWithAll",
}

_TS_PRIMITIVES: dict[str, str] = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


class TsGenError(ValueError):
    """Raised when a schema cannot be mapped to TypeScript (fail-fast)."""


def _type_name(op_id: str) -> str:
    """PascalCase type name derived from a camelCase operation id."""
    return op_id[0].upper() + op_id[1:] if op_id else op_id


def _ts_ident(name: str) -> str:
    """Return ``name`` as a TS field identifier, quoting when not an identifier."""
    if name.isidentifier():
        return name
    return json.dumps(name)


def _enum_type(enum: list[Any], schema_type: str | None) -> str:
    """Render an enum value list as a TS union of literals."""
    literals: list[str] = []
    for value in enum:
        if isinstance(value, bool):
            if schema_type not in (None, "boolean"):
                raise TsGenError(f"enum value {value!r} does not match type {schema_type!r}")
            literals.append("true" if value else "false")
        elif isinstance(value, (int, float)):
            if schema_type not in (None, "integer", "number"):
                raise TsGenError(f"enum value {value!r} does not match type {schema_type!r}")
            literals.append(json.dumps(value))
        elif isinstance(value, str):
            if schema_type not in (None, "string"):
                raise TsGenError(f"enum value {value!r} does not match type {schema_type!r}")
            literals.append(json.dumps(value))
        else:
            raise TsGenError(f"unsupported enum value: {value!r}")
    if not literals:
        raise TsGenError("empty enum")
    return " | ".join(literals)


def _validate_keys(schema: dict[str, Any], context: str) -> None:
    unknown = set(schema) - _STRUCTURAL_KEYS - _METADATA_KEYS
    if unknown:
        raise TsGenError(f"{context}: unsupported schema keyword(s): {sorted(unknown)}")


def _schema_to_ts(
    schema: Any,
    *,
    doc: dict[str, Any],
    context: str,
    enum_names: dict[frozenset[str], str],
    ref_stack: tuple[str, ...] = (),
) -> str:
    """Map one JSON Schema to a TS type expression (fail-fast on unknowns)."""
    if schema is None:
        return "unknown"
    if not isinstance(schema, dict):
        raise TsGenError(f"{context}: schema must be an object, got {schema!r}")
    _validate_keys(schema, context)

    if "$ref" in schema:
        ref = str(schema["$ref"])
        if not ref.startswith("#/components/schemas/"):
            raise TsGenError(f"{context}: unsupported $ref target: {ref!r}")
        name = ref[len("#/components/schemas/") :]
        if name in ref_stack:
            raise TsGenError(f"{context}: circular $ref: {name!r}")
        schemas = (doc.get("components") or {}).get("schemas") or {}
        if name not in schemas:
            raise TsGenError(f"{context}: missing $ref target: {ref!r}")
        return _schema_to_ts(
            schemas[name],
            doc=doc,
            context=context,
            enum_names=enum_names,
            ref_stack=(*ref_stack, name),
        )

    if not schema:
        return "unknown"

    if "oneOf" in schema or "anyOf" in schema:
        variants: list[Any] = schema.get("oneOf") or schema.get("anyOf") or []
        if not variants:
            raise TsGenError(f"{context}: empty oneOf/anyOf")
        return " | ".join(
            _schema_to_ts(
                item, doc=doc, context=context, enum_names=enum_names, ref_stack=ref_stack
            )
            for item in variants
        )
    if "allOf" in schema:
        variants = schema.get("allOf") or []
        if not variants:
            raise TsGenError(f"{context}: empty allOf")
        parts = []
        for item in variants:
            item_ts = _schema_to_ts(
                item, doc=doc, context=context, enum_names=enum_names, ref_stack=ref_stack
            )
            parts.append(f"({item_ts})")
        return " & ".join(parts)
    if "not" in schema:
        raise TsGenError(f"{context}: 'not' is not supported")

    schema_type = schema.get("type")
    if schema_type is None:
        raise TsGenError(
            f"{context}: schema without 'type' is not supported (got keys {sorted(schema)})"
        )

    if "enum" in schema:
        enum = schema["enum"]
        if all(isinstance(value, str) for value in enum) and frozenset(enum) in enum_names:
            rendered = enum_names[frozenset(enum)]
        else:
            rendered = _enum_type(enum, schema_type)
    elif schema_type == "array":
        if "items" not in schema:
            raise TsGenError(f"{context}: array schema without 'items'")
        items_ts = _schema_to_ts(
            schema["items"], doc=doc, context=context, enum_names=enum_names, ref_stack=ref_stack
        )
        rendered = f"Array<{items_ts}>"
    elif schema_type == "object":
        rendered = _object_to_ts(
            schema, doc=doc, context=context, enum_names=enum_names, ref_stack=ref_stack
        )
    elif schema_type in _TS_PRIMITIVES:
        rendered = _TS_PRIMITIVES[schema_type]
    else:
        raise TsGenError(f"{context}: unknown type {schema_type!r}")

    if schema.get("nullable"):
        rendered = f"{rendered} | null"
    return rendered


def _object_to_ts(
    schema: dict[str, Any],
    *,
    doc: dict[str, Any],
    context: str,
    enum_names: dict[frozenset[str], str],
    ref_stack: tuple[str, ...],
) -> str:
    properties = schema.get("properties") or {}
    if not isinstance(properties, dict):
        raise TsGenError(f"{context}: 'properties' must be an object")
    required = set(schema.get("required") or ())
    fields: list[str] = []
    for name in sorted(properties):
        prop_schema = properties[name]
        prop_ts = _schema_to_ts(
            prop_schema,
            doc=doc,
            context=f"{context}.{name}",
            enum_names=enum_names,
            ref_stack=ref_stack,
        )
        optional = "" if name in required else "?"
        fields.append(f"{_ts_ident(name)}{optional}: {prop_ts}")
    additional = schema.get("additionalProperties", True)
    if isinstance(additional, dict):
        value_ts = _schema_to_ts(
            additional,
            doc=doc,
            context=f"{context}[additional]",
            enum_names=enum_names,
            ref_stack=ref_stack,
        )
        fields.append(f"[key: string]: {value_ts}")
    if not fields:
        return "Record<string, unknown>"
    return "{" + "; ".join(fields) + "}"


def _iter_operations(doc: dict[str, Any]) -> Iterable[tuple[str, str, dict[str, Any]]]:
    """Yield (path, method, operation) sorted deterministically."""
    for path in sorted(doc.get("paths") or {}):
        for method in sorted(doc["paths"][path]):
            yield path, method, doc["paths"][path][method]


def _collect_enums(doc: dict[str, Any]) -> dict[frozenset[str], str]:
    """Map distinct enum value sets found in the document to generated names."""
    found: dict[frozenset[str], str] = {}
    for _path, _method, operation in _iter_operations(doc):
        for param in operation.get("parameters") or ():
            schema = param.get("schema") or {}
            enum = schema.get("enum")
            if isinstance(enum, list) and all(isinstance(value, str) for value in enum):
                key = frozenset(enum)
                if key in _ENUM_TYPE_NAMES:
                    found.setdefault(key, _ENUM_TYPE_NAMES[key])
    return found


def _param_ts_type(
    param: dict[str, Any],
    *,
    doc: dict[str, Any],
    context: str,
    enum_names: dict[frozenset[str], str],
) -> str:
    schema = param.get("schema") or {}
    return _schema_to_ts(schema, doc=doc, context=context, enum_names=enum_names)


def _response_schema(
    operation: dict[str, Any],
    *,
    doc: dict[str, Any],
    context: str,
    enum_names: dict[frozenset[str], str],
) -> str:
    response = (operation.get("responses") or {}).get("200") or {}
    content = response.get("content") or {}
    schema = (content.get("application/json") or {}).get("schema")
    return _schema_to_ts(schema, doc=doc, context=context, enum_names=enum_names)


def generate_types_ts(doc: dict[str, Any]) -> str:
    """Generate ``types.ts`` for an OpenAPI document."""
    enum_names = _collect_enums(doc)
    lines: list[str] = [_HEADER]

    if enum_names:
        lines.append(
            "/* Named enum value sets found in the document (deterministic derivation). */"
        )
        for enum_set in sorted(enum_names, key=lambda values: sorted(values)):
            name = enum_names[enum_set]
            values = " | ".join(json.dumps(value) for value in sorted(enum_set))
            lines.append(f"export type {name} = {values};")
        lines.append("")

    for path, method, operation in _iter_operations(doc):
        op_id = str(operation["operationId"])
        type_name = _type_name(op_id)
        lines.append(f"/** {method.upper()} {path} - {operation.get('summary') or ''} */")
        params_ts: list[str] = []
        for param in operation.get("parameters") or ():
            field = _ts_ident(str(param["name"]))
            optional = "" if param.get("required") else "?"
            field_ts = _param_ts_type(
                param, doc=doc, context=f"{op_id}.{param['name']}", enum_names=enum_names
            )
            params_ts.append(f"{field}{optional}: {field_ts}")
        if params_ts:
            lines.append(f"export interface {type_name}Params {{")
            for field in params_ts:
                lines.append(f"  {field};")
            lines.append("}")
        else:
            lines.append(f"export interface {type_name}Params {{}}")
        response_schema = _response_schema(
            operation, doc=doc, context=f"{op_id}.response", enum_names=enum_names
        )
        lines.append(f"export type {type_name}Response = {response_schema};")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _has_etag(operation: dict[str, Any]) -> bool:
    response = (operation.get("responses") or {}).get("200") or {}
    return "ETag" in (response.get("headers") or {})


def _tag_for_path(path: str) -> str:
    """Derive a tag from the first path segment after /api (deterministic)."""
    parts = [part for part in path.split("/") if part and part != "api"]
    return parts[0] if parts else "root"


def generate_client_ts(doc: dict[str, Any]) -> str:
    """Generate ``client.ts`` for an OpenAPI document."""
    lines: list[str] = [_HEADER]
    lines.append("import type {")
    param_types: list[str] = []
    for _path, _method, operation in _iter_operations(doc):
        type_name = _type_name(str(operation["operationId"]))
        param_types.append(f"  {type_name}Params,")
        param_types.append(f"  {type_name}Response,")
    param_types.append('} from "./types.ts";')
    lines.extend(param_types)
    lines.append("")
    lines.extend(_CLIENT_HELPERS)
    lines.append("")

    by_tag: dict[str, list[dict[str, Any]]] = {}
    operations: list[dict[str, Any]] = []
    for path, method, operation in _iter_operations(doc):
        operations.append({"path": path, "method": method, "operation": operation})
    for entry in sorted(operations, key=lambda e: (e["path"], e["method"])):
        tag = _tag_for_path(entry["path"])
        by_tag.setdefault(tag, []).append(entry)

    for tag in sorted(by_tag):
        lines.append(f"/* ---- tag: {tag} ---- */")
        for entry in by_tag[tag]:
            path, method, operation = entry["path"], entry["method"], entry["operation"]
            op_id = str(operation["operationId"])
            lines.append(_client_function(path, method, operation, op_id, doc))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _client_function(
    path: str, method: str, operation: dict[str, Any], op_id: str, doc: dict[str, Any]
) -> str:
    """Render one typed client function."""
    params = operation.get("parameters") or ()
    type_name = _type_name(op_id)
    query_or_path = any(param.get("in") in ("query", "path") for param in params)
    etag = _has_etag(operation)
    return_ts = "Promise<T | null>" if etag else "Promise<T>"
    call = "ccGetEtag" if etag else ("ccGet" if method.lower() == "get" else "ccSend")

    if method.lower() == "get":
        if query_or_path:
            args = f"params: {type_name}Params = {{}}, opts: CcRequestOptions = {{}}"
            target = f'buildPath("{path}", params)'
        else:
            args = "opts: CcRequestOptions = {}"
            target = f'"{path}"'
        return (
            f"export async function {op_id}<T = {type_name}Response>("
            f"{args}): {return_ts} {{\n"
            f"  return {call}<T>({target}, opts);\n"
            f"}}"
        )

    # POST / DELETE: no requestBody schema in the document, so body is untyped.
    if query_or_path:
        args = (
            f"params: {type_name}Params, body: unknown = undefined, opts: CcRequestOptions = {{}}"
        )
        target = f'buildPath("{path}", params)'
    else:
        args = "body: unknown = undefined, opts: CcRequestOptions = {}"
        target = f'"{path}"'
    return (
        f"export async function {op_id}<T = {type_name}Response>("
        f"{args}): Promise<T> {{\n"
        f"  return {call}<T>(\n"
        f"    {target},\n"
        f'    {{ method: "{method.upper()}", '
        f'headers: body === undefined ? undefined : {{ "Content-Type": "application/json" }}, '
        f"body: body === undefined ? undefined : JSON.stringify(body) }},\n"
        f"    opts,\n"
        f"  );\n"
        f"}}"
    )


_CLIENT_HELPERS = [
    "/** 请求选项：超时（AbortController）+ 附加请求头（如 X-Shop-Cookie）。 */",
    "export interface CcRequestOptions {",
    "  readonly timeoutMs?: number;",
    "  readonly headers?: Readonly<Record<string, string>>;",
    "}",
    "",
    "const DEFAULT_TIMEOUT_MS = 20000;",
    "const ETAG_CACHE = new Map<string, string>();",
    "",
    "async function rawFetch(",
    "  path: string,",
    "  init: RequestInit,",
    "  opts: CcRequestOptions,",
    "  etag: boolean,",
    "): Promise<Response> {",
    "  const ctrl = new AbortController();",
    "  const timer = setTimeout(() => ctrl.abort(), opts.timeoutMs ?? DEFAULT_TIMEOUT_MS);",
    "  try {",
    "    const headers = new Headers(init.headers ?? {});",
    "    if (opts.headers) {",
    "      for (const [key, value] of Object.entries(opts.headers)) headers.set(key, value);",
    "    }",
    "    if (etag) {",
    "      const cached = ETAG_CACHE.get(path);",
    '      if (cached) headers.set("if-none-match", cached);',
    "    }",
    '    return await fetch(path, { ...init, headers, cache: "no-store", signal: ctrl.signal });',
    "  } finally {",
    "    clearTimeout(timer);",
    "  }",
    "}",
    "",
    "async function ensureOk(res: Response): Promise<void> {",
    "  if (res.ok) return;",
    "  const data = (await res.json().catch(() => ({}))) as { error?: string; message?: string };",
    "  throw new Error(data.error ?? data.message ?? `HTTP ${res.status}`);",
    "}",
    "",
    "/** 底层 GET：no-store + 超时；非 2xx 抛 Error（优先取 body.error/message）。 */",
    "export async function ccGet<T>(path: string, opts: CcRequestOptions = {}): Promise<T> {",
    "  const res = await rawFetch(path, {}, opts, false);",
    "  await ensureOk(res);",
    "  return (await res.json()) as T;",
    "}",
    "",
    "/** 底层 GET + 弱 ETag 304 协商：304 返回 null（调用方保留旧值）；按 path 缓存 ETag。 */",
    "export async function ccGetEtag<T>(path: string, opts: CcRequestOptions = {}): Promise<T | null> {",  # noqa: E501 - emitted TS line
    "  const res = await rawFetch(path, {}, opts, true);",
    "  if (res.status === 304) return null;",
    "  await ensureOk(res);",
    '  const etag = res.headers.get("etag");',
    "  if (etag) ETAG_CACHE.set(path, etag);",
    "  return (await res.json()) as T;",
    "}",
    "",
    "/** 底层发送（POST/DELETE）：no-store + 超时；非 2xx 抛 Error。 */",
    "export async function ccSend<T>(",
    "  path: string,",
    "  init: RequestInit = {},",
    "  opts: CcRequestOptions = {},",
    "): Promise<T> {",
    "  const res = await rawFetch(path, init, opts, false);",
    "  await ensureOk(res);",
    "  return (await res.json()) as T;",
    "}",
    "",
    "/** 查询串构造：忽略 undefined；值经 encodeURIComponent。 */",
    "export function buildQuery(params: object): string {",
    "  const parts: string[] = [];",
    "  for (const [key, value] of Object.entries(params)) {",
    "    if (value === undefined) continue;",
    "    parts.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`);",
    "  }",
    '  return parts.length > 0 ? `?${parts.join("&")}` : "";',
    "}",
    "",
    "/** 路径模板（/api/registry/agents/{id}）替换 + 查询串。 */",
    "export function buildPath(",
    "  template: string,",
    "  params: object,",
    "): string {",
    "  let path = template;",
    "  const rest: Record<string, unknown> = {};",
    "  for (const [key, value] of Object.entries(params)) {",
    "    if (value === undefined) continue;",
    "    const placeholder = `{${key}}`;",
    "    if (path.includes(placeholder)) {",
    "      path = path.replace(placeholder, encodeURIComponent(String(value)));",
    "    } else {",
    "      rest[key] = value;",
    "    }",
    "  }",
    "  return path + buildQuery(rest);",
    "}",
    "",
]


def generate(doc: dict[str, Any]) -> dict[str, str]:
    """Generate both artifacts for an OpenAPI document."""
    return {"types.ts": generate_types_ts(doc), "client.ts": generate_client_ts(doc)}


def _default_doc() -> dict[str, Any]:
    return build_openapi(RouteTable())


def run_check(verbose: bool = False) -> int:
    """Verify the committed artifacts match a fresh generation (exit 1 on drift)."""
    expected = generate(_default_doc())
    for name in ARTIFACT_NAMES:
        path = GENERATED_DIR / name
        if not path.is_file():
            print(f"[fail] generated artifact missing: {path}", file=sys.stderr)
            return 1
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if actual != expected[name]:
            print(
                f"[fail] generated artifact drift: {path.relative_to(GENERATED_DIR.parents[2])}",
                file=sys.stderr,
            )
            return 1
        if verbose:
            print(f"[ok] {path.relative_to(GENERATED_DIR.parents[2])} ({len(actual)} bytes)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed artifacts (default)")
    parser.add_argument("--emit", action="store_true", help="rewrite generated/ts artifacts")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()
    if args.emit:
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        for name, content in generate(_default_doc()).items():
            (GENERATED_DIR / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {len(ARTIFACT_NAMES)} artifacts to {GENERATED_DIR}")
    return run_check(verbose=args.verbose)


if __name__ == "__main__":
    raise SystemExit(main())
