"""Python control/read API boundary; browser UI lives under apps/.

P5-3: the JSONL / SQLite / cache data base ported from the legacy TypeScript
Command Center lives in the sibling modules (``paths``, ``jsonl``, ``cache``,
``goal_store``, ``human_store``, ``registry``, ``survey_db``).
"""

from .cache import TtlCache
from .errors import CommandCenterError
from .goal_store import (
    DEDUPE_REASON,
    DEFAULT_DEDUPE_WINDOW_MS,
    DEFAULT_GOAL_POLICY,
    GoalEntry,
    GoalKind,
    GoalMutationInput,
    GoalMutationOutcome,
    GoalMutationPolicy,
    GoalMutationResult,
    apply_goal_mutation,
    iso_utc,
)
from .human_override import (
    FAR_STEP,
    STALE_OVERRIDE_MAX_AGE_MS,
    HumanOverrideResult,
    HumanRejection,
    action_from_wire,
    apply_human_overrides,
    basic_check,
    goal_action_for_unit,
    is_stale_override,
    read_and_apply_human_overrides,
)
from .human_store import (
    HUMAN_OVERRIDE_TAIL,
    STUCK_RING_MAX,
    STUCK_TICKS,
    HumanCommand,
    HumanStore,
    StuckEntry,
    cancel_stuck_goals,
    empty_store,
    latest_human_override,
    read_human_store,
    reconcile_human_store,
    stuck_record,
    write_human_store,
)
from .jsonl import (
    RUN_CACHE_TTL_MS,
    append_jsonl,
    latest_run_dir,
    list_cases,
    load_jsonl_rows,
    parse_tick,
    read_jsonl_tail,
    runs_by_max_tick,
)
from .paths import (
    DATA_ROOT_ENV,
    SIM_TENANT_PREFIX,
    TENANTS,
    calibration_dir,
    human_commands_dir,
    human_commands_file,
    normalize_tenant,
    outcome_jsonl_path,
    redeem_log_path,
    registry_db_path,
    resolve_data_root,
    runtime_dir,
    survey_db_path,
    telemetry_dir,
    validate_data_root,
    validate_survey_tenant,
    validate_tenant,
)
from .registry import (
    AGENT_MODES,
    SIMKEY_HEX_BYTES,
    SIMKEY_PREFIX,
    AgentMode,
    RegisteredAgent,
    RegistryKey,
    RegistryStore,
    generate_sim_key,
    sha256_hex,
)
from .survey_db import (
    AGENT_EVENT_KINDS,
    SURVEY_DB_SCHEMA,
    AgentEventKind,
    AgentIngestEvent,
    AgentRow,
    SurveyDb,
)

__all__ = [
    "AGENT_EVENT_KINDS",
    "AGENT_MODES",
    "AgentEventKind",
    "AgentIngestEvent",
    "AgentMode",
    "AgentRow",
    "CommandCenterError",
    "DEDUPE_REASON",
    "DEFAULT_DEDUPE_WINDOW_MS",
    "DEFAULT_GOAL_POLICY",
    "DATA_ROOT_ENV",
    "GoalEntry",
    "GoalKind",
    "GoalMutationInput",
    "GoalMutationOutcome",
    "GoalMutationPolicy",
    "GoalMutationResult",
    "HUMAN_OVERRIDE_TAIL",
    "FAR_STEP",
    "HumanCommand",
    "HumanOverrideResult",
    "HumanRejection",
    "HumanStore",
    "STALE_OVERRIDE_MAX_AGE_MS",
    "RUN_CACHE_TTL_MS",
    "RegisteredAgent",
    "RegistryKey",
    "RegistryStore",
    "SIMKEY_HEX_BYTES",
    "SIMKEY_PREFIX",
    "STUCK_RING_MAX",
    "STUCK_TICKS",
    "SURVEY_DB_SCHEMA",
    "SIM_TENANT_PREFIX",
    "StuckEntry",
    "SurveyDb",
    "TENANTS",
    "TtlCache",
    "apply_goal_mutation",
    "append_jsonl",
    "calibration_dir",
    "cancel_stuck_goals",
    "empty_store",
    "generate_sim_key",
    "human_commands_dir",
    "human_commands_file",
    "iso_utc",
    "latest_human_override",
    "latest_run_dir",
    "list_cases",
    "load_jsonl_rows",
    "normalize_tenant",
    "outcome_jsonl_path",
    "parse_tick",
    "read_human_store",
    "action_from_wire",
    "apply_human_overrides",
    "basic_check",
    "goal_action_for_unit",
    "is_stale_override",
    "read_and_apply_human_overrides",
    "read_jsonl_tail",
    "reconcile_human_store",
    "redeem_log_path",
    "registry_db_path",
    "resolve_data_root",
    "runtime_dir",
    "runs_by_max_tick",
    "sha256_hex",
    "stuck_record",
    "survey_db_path",
    "telemetry_dir",
    "validate_data_root",
    "validate_survey_tenant",
    "validate_tenant",
    "write_human_store",
]
